# Install to:
# ~/.config/geany/colorschemes/nord.conf
#
# Color Palette
# Background 0x2E3440
# Current Line 0x3B4252
# Selection 0x434C5E
# Foreground 0xD8DEE9
# Comment 0x616E88
# Cyan 0x88C0D0
# Green 0xA3BE8C
# Orange 0xD08770
# Purple 0xB48EAD
# Red 0xBF616A
# Yellow 0xEBCB8B
# Blue 0x81A1C1
# White 0xECEFF4

[theme_info]
name=Nord Dracula Hybrid
description=Nord Based on Dracula
version=1.0.0
author=Rob/ChatGPT
url=

[named_styles]

default=0xD8DEE9;0x2E3440
error=0xBF616A


# Editor styles
#-------------------------------------------------------------------------------
selection=0x434C5E
current_line=0x3B4252
brace_good=0xA3BE8C;;true
brace_bad=0xBF616A;;true
margin_line_number=0x616E88;0x2E3440
margin_folding=0x616E88;0x2E3440
fold_symbol_highlight=0x81A1C1
indent_guide=0x616E88
caret=0xD8DEE9
marker_line=0xD8DEE9;0x3B4252
marker_search=0x2E3440;0xEBCB8B
marker_mark=0x2E3440;0x88C0D0
call_tips=0xD8DEE9;0x3B4252
white_space=indent_guide


# Programming languages
#-------------------------------------------------------------------------------
# Go
# Rust
# Java
# HTML
# CSS
# Python
# C#
# C
# C++
# Typesctipt
# Javascript
# Ruby
# And all other languages supported by geany!

comment=0x616E88
comment_doc=comment
comment_line=comment
comment_line_doc=comment_doc
comment_doc_keyword=comment_doc,bold
comment_doc_keyword_error=comment_doc,italic

number=0xB48EAD
number_1=number
number_2=number_1

type=0xB48EAD
class=type
function=0xA3BE8C
parameter=function

keyword=0x88C0D0;;true
keyword_1=keyword
keyword_2=keyword
keyword_3=keyword_1
keyword_4=keyword_1

identifier=default
identifier_1=identifier
identifier_2=identifier
identifier_3=identifier_1
identifier_4=identifier_1

string=0xEBCB8B
string_1=string
string_2=string_1
string_3=default
string_4=default
string_eol=0xBF616A
character=string_1
backtick=string_2
here_doc=string_2

scalar=string_2
label=default,bold
preprocessor=0xD08770
regex=0xB48EAD
operator=0xB48EAD
decorator=string_1,bold
other=default


# Markup-type languages
#-------------------------------------------------------------------------------

tag=type
tag_unknown=tag,bold
tag_end=tag,bold
attribute=keyword_1
attribute_unknown=attribute,bold
value=string_1
entity=default


# Diff
#-------------------------------------------------------------------------------

line_added=0xA3BE8C
line_removed=0xBF616A
line_changed=0x81A1C1
