# Install to:
# ~/.config/geany/colorschemes/qogir.conf
#
# Color Palette
# Background 0x2F343F
# Current Line 0x383C4A
# Selection 0x404552
# Foreground 0xD3DAE3
# Comment 0x777D8A
# Cyan 0x5BC0DE
# Green 0x8AB93D
# Orange 0xF57900
# Purple 0xB294BB
# Red 0xCC575D
# Yellow 0xF6D32D
# Blue 0x5294E2
# White 0xF6F7F8

[theme_info]
name=Qogir Dark
description=Qogir Based on Dracula
version=1.0.0
author=Rob/ChatGPT
url=

[named_styles]

default=0xD3DAE3;0x2F343F
error=0xCC575D


# Editor styles
#-------------------------------------------------------------------------------
selection=0x404552
current_line=0x383C4A
brace_good=0x8AB93D;;true
brace_bad=0xCC575D;;true
margin_line_number=0x777D8A;0x2F343F
margin_folding=0x777D8A;0x2F343F
fold_symbol_highlight=0x5294E2
indent_guide=0x777D8A
caret=0xD3DAE3
marker_line=0xD3DAE3;0x383C4A
marker_search=0x2F343F;0xF6D32D
marker_mark=0x2F343F;0x5BC0DE
call_tips=0xD3DAE3;0x383C4A
white_space=indent_guide


# Programming languages
#-------------------------------------------------------------------------------
# Go
# Rust
# Java
# HTML
# CSS
# Python
# C#
# C
# C++
# Typesctipt
# Javascript
# Ruby
# And all other languages supported by geany!

comment=0x777D8A
comment_doc=comment
comment_line=comment
comment_line_doc=comment_doc
comment_doc_keyword=comment_doc,bold
comment_doc_keyword_error=comment_doc,italic

number=0xB294BB
number_1=number
number_2=number_1

type=0xB294BB
class=type
function=0x8AB93D
parameter=function

keyword=0x5BC0DE;;true
keyword_1=keyword
keyword_2=keyword
keyword_3=keyword_1
keyword_4=keyword_1

identifier=default
identifier_1=identifier
identifier_2=identifier
identifier_3=identifier_1
identifier_4=identifier_1

string=0xF6D32D
string_1=string
string_2=string_1
string_3=default
string_4=default
string_eol=0xCC575D
character=string_1
backtick=string_2
here_doc=string_2

scalar=string_2
label=default,bold
preprocessor=0xF57900
regex=0xB294BB
operator=0xB294BB
decorator=string_1,bold
other=default


# Markup-type languages
#-------------------------------------------------------------------------------

tag=type
tag_unknown=tag,bold
tag_end=tag,bold
attribute=keyword_1
attribute_unknown=attribute,bold
value=string_1
entity=default


# Diff
#-------------------------------------------------------------------------------

line_added=0x8AB93D
line_removed=0xCC575D
line_changed=0x5294E2
